"""empty message

Revision ID: 9b7cfb422191
Revises: 
Create Date: 2021-11-21 14:09:17.478532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b7cfb422191"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(length=8), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "object_id", "object_type", name="uc_cached_files_object_id_object_type"
        ),
    )
    op.create_index(
        op.f("ix_cached_files_object_id"), "cached_files", ["object_id"], unique=False
    )
    op.create_index(
        op.f("ix_cached_files_object_type"),
        "cached_files",
        ["object_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cached_files")
    op.drop_index("ix_cached_files_object_id")
    op.drop_index("ix_cached_files_object_type")
    # ### end Alembic commands ###
